coverage:
  status:
    project:
      default:
        threshold: 1  # Allow coverage to drop t% without giving a failed status
    patch:
      default:
        threshold: 20  # Changed code can have t% lower coverage than overall
