version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.github/dependabot/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
    # We currently only specify a major version of actions (e.g. actions/checkout@v6)
    # So we only want to change it when the major version changes.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
