language: python
python:
  - 3.8
  - 3.7
  - 3.6

env:
  global:
    - MPLBACKEND=agg

install:
  - make install
  - pip install -U pytest  # pytest-cov needs a newer pytest
  - pip install codecov

script:
  - make test

after_success: codecov
